name: Gradle build
on:
  pull_request:
    branches: [main]
  
  workflow_dispatch:

  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run integration tests
        run: ./gradlew functionalTest
